# Generated by Django 4.0.6 on 2022-07-20 21:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matric_number', models.CharField(max_length=15)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=11)),
                ('date_of_birth', models.DateField()),
                ('email', models.CharField(max_length=50)),
                ('aim_objective', models.CharField(max_length=100)),
                ('school_name', models.CharField(max_length=150)),
                ('school_address', models.TextField()),
                ('school_id', models.ImageField(upload_to='media/schoolIds')),
                ('video_file', models.FileField(upload_to='media/applications', validators=[django.core.validators.FileExtensionValidator(['mp4'])])),
                ('photo', models.ImageField(upload_to='media/photos')),
                ('project_source', models.CharField(max_length=10)),
                ('desc', models.TextField()),
                ('project_desc', models.TextField()),
                ('project_benefit', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'students_applications',
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='AssessmentCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_objective', models.IntegerField(choices=[(5, 'Excellent'), (4, 'Good'), (3, 'Average'), (2, 'Poor'), (1, 'Very poor')])),
                ('project_desc', models.IntegerField(choices=[(5, 'Excellent'), (4, 'Good'), (3, 'Average'), (2, 'Poor'), (1, 'Very poor')])),
                ('project_ingenuity', models.IntegerField(choices=[(5, 'Excellent'), (4, 'Good'), (3, 'Average'), (2, 'Poor'), (1, 'Very poor')])),
                ('project_source', models.IntegerField(choices=[(5, 'Excellent'), (4, 'Good'), (3, 'Average'), (2, 'Poor'), (1, 'Very poor')])),
                ('expected_benefit', models.IntegerField(choices=[(5, 'Excellent'), (4, 'Good'), (3, 'Average'), (2, 'Poor'), (1, 'Very poor')])),
                ('presentation_skills', models.IntegerField(choices=[(5, 'Excellent'), (4, 'Good'), (3, 'Average'), (2, 'Poor'), (1, 'Very poor')])),
                ('project_viability', models.IntegerField(choices=[(5, 'Excellent'), (4, 'Good'), (3, 'Average'), (2, 'Poor'), (1, 'Very poor')])),
                ('sustainability', models.IntegerField(choices=[(5, 'Excellent'), (4, 'Good'), (3, 'Average'), (2, 'Poor'), (1, 'Very poor')])),
                ('total_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('applicant_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.application')),
            ],
            options={
                'db_table': 'assessment_criteria',
            },
        ),
    ]
