# Generated by Django 4.0.6 on 2023-01-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_assessmentcriteria_assessor'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAssessment',
            fields=[
                ('unique_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Fullname', models.CharField(max_length=255)),
                ('Institution', models.CharField(max_length=255)),
                ('PresentationSkills', models.IntegerField()),
                ('ExpectedBenefits', models.IntegerField()),
                ('ProjectDesc', models.IntegerField()),
                ('ProjectIngenuity', models.IntegerField()),
                ('ProjectViability', models.IntegerField()),
                ('Sustainability', models.IntegerField()),
                ('ProjectSource', models.IntegerField()),
                ('ProjectObjective', models.IntegerField()),
                ('TotalScore', models.IntegerField()),
                ('AverageScore', models.FloatField()),
            ],
            options={
                'db_table': 'student_assessment',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='application',
            name='project_title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
