# Generated by Django 4.0.6 on 2022-07-16 12:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=50)),
                ('school_name', models.CharField(max_length=150)),
                ('school_address', models.TextField()),
                ('desc', models.TextField()),
                ('school_id', models.ImageField(upload_to='media/schoolIds')),
                ('video_file', models.FileField(upload_to='media/applications', validators=[django.core.validators.FileExtensionValidator(['mp4'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
